// ★ The shapes that are valid OpenAPI and produce a broken client.
//
// A contract is not only read by humans and by `openapi-typescript`. The Dart
// client is generated by openapi-generator's `dart-dio` target, and the two do
// not agree about everything — so a construct can be correct, expressive,
// pass `redocly lint`, and still leave one of our two apps unable to call the
// endpoint at all.
//
// ── The one that happened ────────────────────────────────────────────────
// `SignupResponse.verified` was `type: boolean` with `enum: [false]`, meaning
// "a new account is never verified". `dart-dio` read the `enum` as a TYPE and
// emitted an `EnumClass` whose sole wire value is the STRING "false". The API
// sends the JSON boolean, so deserialization threw inside the generated method
// and every mobile signup failed with `ApiError(status: 201)` — the server
// saying "created" and the client unable to read the answer.
//
// It survived because five mobile test files had been changed to send
// `'verified': 'false'` as a string, with comments explaining that built_value
// wanted it that way: the fakes had been fitted to the CLIENT rather than to
// the SERVER, so the suite reproduced the bug faithfully and passed. Found by
// E-10, on an emulator, against a real API (tasks.md, 2026-08-17).
//
// The same shape was on `OkResponse.ok` — logout, logout-all and
// change-password all return it — and on `ReissuedLink.rotated`.
//
// This test reads the bundle, so it sees exactly what the generators see.
import { readFileSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { describe, it, expect } from "vitest";

const PACKAGE_ROOT = (() => {
  let dir = resolve(process.cwd());
  for (;;) {
    if (existsSync(join(dir, "openapi", "root.yaml"))) return dir;
    const parent = dirname(dir);
    if (parent === dir) {
      throw new Error(`generator-hostile-shapes: no openapi/root.yaml above ${process.cwd()}`);
    }
    dir = parent;
  }
})();

const BUNDLE = join(PACKAGE_ROOT, "openapi", "openapi.yaml");

export interface BooleanEnum {
  readonly line: number;
  readonly snippet: string;
}

/**
 * Every `type: boolean` that is followed by an `enum:` inside the same
 * property block.
 *
 * Deliberately textual rather than a YAML walk: the bundle is what the
 * generators consume, "the next line at deeper-or-equal indentation" is
 * exactly how this construct appears, and a parser here would need the same
 * schema-composition rules the generators disagree about.
 */
export function findBooleanEnums(yaml: string): BooleanEnum[] {
  const lines = yaml.split("\n");
  const found: BooleanEnum[] = [];

  for (let i = 0; i < lines.length; i++) {
    const match = /^(\s*)type:\s*boolean\s*$/.exec(lines[i]);
    if (!match) continue;
    const indent = match[1].length;

    // Scan the rest of this property's block: same indentation is a sibling
    // key, less is the end of the block.
    for (let j = i + 1; j < lines.length; j++) {
      const line = lines[j];
      if (line.trim() === "") continue;
      const lineIndent = line.length - line.trimStart().length;
      if (lineIndent < indent) break;
      if (lineIndent === indent && /^\s*enum:/.test(line)) {
        found.push({ line: j + 1, snippet: `${lines[i].trim()} … ${line.trim()}` });
        break;
      }
      if (lineIndent === indent && !/^\s*(enum|description|example|default|title):/.test(line)) {
        break;
      }
    }
  }
  return found;
}

describe("★ shapes that generate a broken client", () => {
  const bundle = readFileSync(BUNDLE, "utf8");

  it("the bundle was actually read", () => {
    // A scan over an empty string passes every ban ever written.
    expect(bundle.length).toBeGreaterThan(10_000);
    expect(bundle).toContain("SignupResponse");
  });

  it("SELF-CHECK: the scan finds the exact shape that broke mobile, and spares the rest", () => {
    const bad = findBooleanEnums(
      ["    verified:", "      type: boolean", "      enum:", "        - false"].join("\n"),
    );
    expect(bad, "the scan would not have caught the bug it exists for").toHaveLength(1);

    // A string enum is fine — that is what enums are for.
    expect(
      findBooleanEnums(
        ["    status:", "      type: string", "      enum:", "        - active"].join("\n"),
      ),
    ).toHaveLength(0);

    // A boolean with a description, and a DIFFERENT property carrying an enum
    // further down, must not be conflated.
    expect(
      findBooleanEnums(
        [
          "    isOwner:",
          "      type: boolean",
          "      description: Does this row's role hold full_access?",
          "    status:",
          "      type: string",
          "      enum:",
          "        - active",
        ].join("\n"),
      ),
    ).toHaveLength(0);
  });

  it("★ no boolean carries an `enum` — it is a comment that dart-dio reads as a type", () => {
    const offenders = findBooleanEnums(bundle);
    expect(
      offenders.map((o) => `openapi.yaml:${o.line} — ${o.snippet}`),
      "a boolean with an enum becomes a STRING-valued EnumClass in the Dart client, and the " +
        "endpoint stops working. Say it in `description:` instead.",
    ).toEqual([]);
  });
});
