// F-001 · T-001-01 / T-001-04 — access-token claim builder (PURE fn).
// arch §1.1/§2.2: the access JWT claim set is DELIBERATELY MINIMAL and is a
// regression guard (M-9 / test U2.4): EXACTLY { sub, iat, exp, jti, typ } — NO
// email (PII), NO organizationId, NO role, NO capabilities. `sub` = User.id;
// `typ = "access"` so a refresh token can never be replayed as an access token.
//
// Building the claims as a pure fn (values in → object out, no signing, no
// clock unless injected) means the "no PII / no org / no role" invariant is
// unit-testable without the JWT library — the service's signing call site
// consumes exactly this object, and I2.10 re-asserts it on the wire-issued token.

/** Access-token TTL in seconds (arch §2.2 — 15 minutes). */
export const ACCESS_TOKEN_TTL_SECONDS = 15 * 60;

/** The literal token-type claim for an access token (type-confusion defense). */
export const ACCESS_TOKEN_TYP = "access" as const;

/**
 * The EXACT claim set for an access token. This interface is the contract the
 * M-9 regression test pins — adding a field here (and only here) is the single
 * deliberate place a new claim could be introduced, and the test forbids PII/
 * org/role fields.
 */
export interface AccessTokenClaims {
  /** Subject = User.id. */
  sub: string;
  /** Issued-at, epoch SECONDS. */
  iat: number;
  /** Expiry, epoch SECONDS (= iat + ACCESS_TOKEN_TTL_SECONDS). */
  exp: number;
  /** Unique token id for log correlation (NOT looked up on the hot path). */
  jti: string;
  /** Token type — always "access". */
  typ: typeof ACCESS_TOKEN_TYP;
}

export interface BuildAccessClaimsInput {
  /** The authenticated user's id (→ `sub`). */
  userId: string;
  /** A unique id for this token (→ `jti`). Generated by the caller (CSPRNG). */
  jti: string;
  /** Issued-at, epoch SECONDS. Injected so the fn stays pure/testable. */
  nowSeconds: number;
  /** Override TTL (seconds); defaults to the 15-min constant. */
  ttlSeconds?: number;
}

/**
 * Assemble the minimal access-token claims. Returns an object whose key set is
 * EXACTLY { sub, iat, exp, jti, typ } — no spread of caller data, no optional
 * extras. `exp − iat === ttlSeconds` (default 900).
 */
export function buildAccessClaims(input: BuildAccessClaimsInput): AccessTokenClaims {
  const ttl = input.ttlSeconds ?? ACCESS_TOKEN_TTL_SECONDS;
  const iat = input.nowSeconds;
  return {
    sub: input.userId,
    iat,
    exp: iat + ttl,
    jti: input.jti,
    typ: ACCESS_TOKEN_TYP,
  };
}
